# TensorFlow基础

In [1]:
import tensorflow as tf
import tensorflow.keras as keras
import tensorflow.keras.layers as layers

physical_devices = tf.config.experimental.list_physical_devices('GPU')
assert len(physical_devices) > 0, "Not enough GPU hardware devices available"
tf.config.experimental.set_memory_growth(physical_devices[0], True)

## 数据类型

### 数值类型

标量在 TensorFlow 是如何创建的

In [2]:
# python 语言方式创建标量
a = 1.2 
# TF 方式创建标量
aa = tf.constant(1.2)

type(a), type(aa), tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

如果要使用 TensorFlow 提供的功能函数， 须通过 TensorFlow 规定的方式去创建张量，而不能使用 Python 语言的标准变量创建方式。

In [3]:
x = tf.constant([1,2.,3.3])
# 打印 TF 张量的相关信息                
x

<tf.Tensor: id=1, shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.3], dtype=float32)>

In [4]:
# 将 TF 张量的数据导出为 numpy 数组格式
x.numpy() 

array([1. , 2. , 3.3], dtype=float32)

与标量不同，向量的定义须通过 List 容器传给 tf.constant()函数。

创建一个元素的向量：

In [5]:
# 创建一个元素的向量
a = tf.constant([1.2]) 
a, a.shape

(<tf.Tensor: id=2, shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>,
 TensorShape([1]))

创建 3 个元素的向量：

In [6]:
 # 创建 3 个元素的向量
a = tf.constant([1,2, 3.])
a, a.shape

(<tf.Tensor: id=3, shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 TensorShape([3]))

定义矩阵

In [7]:
# 创建 2 行 2 列的矩阵
a = tf.constant([[1,2],[3,4]]) 
a, a.shape

(<tf.Tensor: id=4, shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>, TensorShape([2, 2]))

三维张量可以定义为：

In [8]:
# 创建 3 维张量
tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]]) 

<tf.Tensor: id=5, shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])>

通过传入字符串对象即可创建字符串类型的张量

In [9]:
# 创建字符串
a = tf.constant('Hello, Deep Learning.') 
a

<tf.Tensor: id=6, shape=(), dtype=string, numpy=b'Hello, Deep Learning.'>

### 字符串类型

通过传入字符串对象即可创建字符串类型的张量

In [10]:
# 创建字符串
a = tf.constant('Hello, Deep Learning.') 
a

<tf.Tensor: id=7, shape=(), dtype=string, numpy=b'Hello, Deep Learning.'>

在 tf.strings 模块中，提供了常见的字符串类型的工具函数，如小写化 lower()、 拼接
join()、 长度 length()、 切分 split()等。

In [11]:
# 小写化字符串
tf.strings.lower(a) 

<tf.Tensor: id=8, shape=(), dtype=string, numpy=b'hello, deep learning.'>

### 布尔类型
布尔类型的张量只需要传入 Python 语言的布尔类型数据，转换成 TensorFlow 内部布尔型即可。

In [12]:
# 创建布尔类型标量
tf.constant(True) 

<tf.Tensor: id=9, shape=(), dtype=bool, numpy=True>

创建布尔类型的向量

In [13]:
 # 创建布尔类型向量
tf.constant([True, False])

<tf.Tensor: id=10, shape=(2,), dtype=bool, numpy=array([ True, False])>

需要注意的是， TensorFlow 的布尔类型和 Python 语言的布尔类型并不等价，不能通用

In [14]:
# 创建 TF 布尔张量
a = tf.constant(True) 
# TF 布尔类型张量与 python 布尔类型比较
print(a is True) 
# 仅数值比较
print(a == True) 

False
tf.Tensor(True, shape=(), dtype=bool)


## 数值精度

在创建张量时，可以指定张量的保存精度

In [15]:
# 创建指定精度的张量
tf.constant(123456789, dtype=tf.int16)

<tf.Tensor: id=14, shape=(), dtype=int16, numpy=-13035>

In [16]:
tf.constant(123456789, dtype=tf.int32)

<tf.Tensor: id=15, shape=(), dtype=int32, numpy=123456789>

对于浮点数， 高精度的张量可以表示更精准的数据，例如采用 tf.float32 精度保存π时，实际保存的数据为 3.1415927

In [17]:
import numpy as np
# 从 numpy 中导入 pi 常量
np.pi 
# 32 位
tf.constant(np.pi, dtype=tf.float32) 

<tf.Tensor: id=16, shape=(), dtype=float32, numpy=3.1415927>

如果采用 tf.float64 精度保存π，则能获得更高的精度

In [18]:
tf.constant(np.pi, dtype=tf.float64) # 64 位

<tf.Tensor: id=17, shape=(), dtype=float64, numpy=3.141592653589793>

### 读取精度

通过访问张量的 dtype 成员属性可以判断张量的保存精度

In [19]:
a = tf.constant(np.pi, dtype=tf.float16)

# 读取原有张量的数值精度
print('before:',a.dtype) 
# 如果精度不符合要求，则进行转换
if a.dtype != tf.float32: 
    # tf.cast 函数可以完成精度转换
    a = tf.cast(a,tf.float32) 
# 打印转换后的精度
print('after :',a.dtype) 

before: <dtype: 'float16'>
after : <dtype: 'float32'>


### 类型转换
系统的每个模块使用的数据类型、 数值精度可能各不相同， 对于不符合要求的张量的类型及精度， 需要通过 tf.cast 函数进行转换

In [20]:
# 创建 tf.float16 低精度张量
a = tf.constant(np.pi, dtype=tf.float16) 
# 转换为高精度张量
tf.cast(a, tf.double) 

<tf.Tensor: id=21, shape=(), dtype=float64, numpy=3.140625>

进行类型转换时，需要保证转换操作的合法性， 例如将高精度的张量转换为低精度的张量时，可能发生数据溢出隐患：

In [21]:
a = tf.constant(123456789, dtype=tf.int32)
# 转换为低精度整型
tf.cast(a, tf.int16) 

<tf.Tensor: id=23, shape=(), dtype=int16, numpy=-13035>

布尔类型与整型之间相互转换也是合法的， 是比较常见的操作

In [22]:
a = tf.constant([True, False])
# 布尔类型转整型
tf.cast(a, tf.int32) 

<tf.Tensor: id=25, shape=(2,), dtype=int32, numpy=array([1, 0])>

一般默认 0 表示 False， 1 表示 True，在 TensorFlow 中，将非 0 数字都视为 True，

In [23]:
a = tf.constant([-1, 0, 1, 2])
# 整型转布尔类型
tf.cast(a, tf.bool) 

<tf.Tensor: id=27, shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

## 待优化张量

TensorFlow 增加了一种专门的数据类型来支持梯度信息的记录： tf.Variable。 tf.Variable 类型在普通的张量类型基础上添加了 name， trainable 等属性来支持计算图的构建。

In [24]:
# 创建 TF 张量
a = tf.constant([-1, 0, 1, 2]) 
# 转换为 Variable 类型
aa = tf.Variable(a) 
# Variable 类型张量的属性
aa.name, aa.trainable 

('Variable:0', True)

name 属性用于命名计算图中的变量，这套命名体系是 TensorFlow 内部维护的， 一般不需要用户关注 name 属性；   
trainable属性表征当前张量是否需要被优化，创建 Variable 对象时是默认启用优化标志，可以设置trainable=False 来设置张量不需要优化。

In [25]:
# 直接创建 Variable 张量
tf.Variable([[1,2],[3,4]]) 

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

## 创建张量

### 从数组、列表对象创建



通过 tf.convert_to_tensor 函数可以创建新 Tensor，并将保存在 Python List 对象或者Numpy Array 对象中的数据导入到新 Tensor 中。

In [26]:
# 从列表创建张量
tf.convert_to_tensor([1,2.]) 

<tf.Tensor: id=44, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [27]:
# 从数组中创建张量
tf.convert_to_tensor(np.array([[1,2.],[3,4]])) 

<tf.Tensor: id=45, shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

### 创建全 0 或全 1 张量

In [28]:
# 创建全 0，全 1 的标量
tf.zeros([]),tf.ones([]) 

(<tf.Tensor: id=46, shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: id=47, shape=(), dtype=float32, numpy=1.0>)

In [29]:
# 创建全 0，全 1 的向量
tf.zeros([1]),tf.ones([1]) 

(<tf.Tensor: id=50, shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Tensor: id=53, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)

创建全 0 的矩阵

In [30]:
# 创建全 0 矩阵，指定 shape 为 2 行 2 列
tf.zeros([2,2]) 

<tf.Tensor: id=56, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

创建全 1 的矩阵

In [31]:
# 创建全 1 矩阵，指定 shape 为 3 行 2 列
tf.ones([3,2]) 

<tf.Tensor: id=59, shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

通过 tf.zeros_like, tf.ones_like 可以方便地新建与某个张量 shape 一致， 且内容为全 0 或全 1 的张量。

In [32]:
# 创建一个矩阵
a = tf.ones([2,3]) 
# 创建一个与 a 形状相同，但是全 0 的新矩阵
tf.zeros_like(a) 

<tf.Tensor: id=63, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

创建与张量A形状一样的全 1 张量

In [33]:
# 创建一个矩阵
a = tf.zeros([3,2]) 
# 创建一个与 a 形状相同，但是全 1 的新矩阵
tf.ones_like(a) 

<tf.Tensor: id=69, shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

### 创建自定义数值张量

通过 tf.fill(shape, value)可以创建全为自定义数值 value 的张量，形状由 shape 参数指定。

In [34]:
# 创建-1 的标量
tf.fill([], -1) 

<tf.Tensor: id=72, shape=(), dtype=int32, numpy=-1>

In [35]:
# 创建-1 的向量
tf.fill([1], -1) 

<tf.Tensor: id=75, shape=(1,), dtype=int32, numpy=array([-1])>

In [36]:
# 创建 2 行 2 列，元素全为 99 的矩阵
tf.fill([2,2], 99) 

<tf.Tensor: id=78, shape=(2, 2), dtype=int32, numpy=
array([[99, 99],
       [99, 99]])>

### 创建已知分布的张量

通过 tf.random.normal(shape, mean=0.0, stddev=1.0)可以创建形状为 shape，均值为mean，标准差为 stddev 的正态分布$\mathcal{N}(mean, stddev^2)$。

In [37]:
# 创建标准正态分布的张量
tf.random.normal([2,2]) 

<tf.Tensor: id=84, shape=(2, 2), dtype=float32, numpy=
array([[-0.6773533,  0.4303947],
       [-0.6848586, -0.8139115]], dtype=float32)>

In [38]:
# 创建均值为 1，标准差为 2 的正态分布的张量
tf.random.normal([2,2], mean=1,stddev=2) 

<tf.Tensor: id=90, shape=(2, 2), dtype=float32, numpy=
array([[-1.3525722 , -2.0717647 ],
       [-0.90770876, -0.6303625 ]], dtype=float32)>

通过 tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32)可以创建采样自[minval, maxval)区间的均匀分布的张量

In [39]:
# 创建采样自[0,1)均匀分布的矩阵
tf.random.uniform([3,2]) 

<tf.Tensor: id=97, shape=(3, 2), dtype=float32, numpy=
array([[0.667807  , 0.9174658 ],
       [0.4037068 , 0.41466045],
       [0.7332729 , 0.92621017]], dtype=float32)>

In [40]:
# 创建采样自[0,10)均匀分布的矩阵
tf.random.uniform([2,2],maxval=10) 

<tf.Tensor: id=104, shape=(2, 2), dtype=float32, numpy=
array([[2.81173  , 1.8799245],
       [8.92116  , 8.153972 ]], dtype=float32)>

如果需要均匀采样整形类型的数据，必须指定采样区间的最大值 maxval 参数，同时指定数据类型为 tf.int*型

In [41]:
# 创建采样自[0,100)均匀分布的整型矩阵
tf.random.uniform([2,2],maxval=100,dtype=tf.int32)

<tf.Tensor: id=108, shape=(2, 2), dtype=int32, numpy=
array([[20, 94],
       [25, 88]])>

### 创建序列

tf.range(limit, delta=1)可以创建[0, limit)之间，步长为 delta 的整型序列，不包含 limit 本身。

In [42]:
# 0~10，不包含 10
tf.range(10) 

<tf.Tensor: id=112, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [43]:
# 创建 0~10，步长为 2 的整形序列
tf.range(10,delta=2)

<tf.Tensor: id=116, shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8])>

In [44]:
tf.range(1,10,delta=2) # 1~10

<tf.Tensor: id=120, shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

## 张量的典型应用

### 标量

In [45]:
# 随机模拟网络输出
out = tf.random.uniform([4,10]) 
# 随机构造样本真实标签
y = tf.constant([2,3,2,0]) 
# one-hot 编码
y = tf.one_hot(y, depth=10) 
# 计算每个样本的 MSE
loss = tf.keras.losses.mse(y, out) 
# 平均 MSE,loss 应是标量
loss = tf.reduce_mean(loss) 
print(loss)

tf.Tensor(0.4076194, shape=(), dtype=float32)


### 向量

考虑 2 个输出节点的网络层， 我们创建长度为 2 的偏置向量b，并累加在每个输出节点上：

In [46]:
# z=wx,模拟获得激活函数的输入 z
z = tf.random.normal([4,2])
# 创建偏置向量
b = tf.zeros([2])
# 累加上偏置向量
z = z + b 
z

<tf.Tensor: id=147, shape=(4, 2), dtype=float32, numpy=
array([[ 0.9726034 ,  1.418436  ],
       [ 0.1870317 ,  0.536654  ],
       [ 0.07191976, -0.7674028 ],
       [-0.36163288, -0.28200135]], dtype=float32)>

创建输入节点数为 4，输出节点数为 3 的线性层网络，那么它的偏置向量 b 的长度应为 3

In [47]:
# 创建一层 Wx+b，输出节点为 3
fc = tf.keras.layers.Dense(3) 
# 通过 build 函数创建 W,b 张量，输入节点为 4
fc.build(input_shape=(2,4))
# 查看偏置向量
fc.bias 

<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

### 矩阵

In [48]:
# 2 个样本，特征长度为 4 的张量
x = tf.random.normal([2,4]) 
# 定义 W 张量
w = tf.ones([4,3])
# 定义 b 张量
b = tf.zeros([3]) 
# X@W+b 运算
o = x@w+b 
o

<tf.Tensor: id=185, shape=(2, 3), dtype=float32, numpy=
array([[0.8772295, 0.8772295, 0.8772295],
       [1.740916 , 1.740916 , 1.740916 ]], dtype=float32)>

In [49]:
# 定义全连接层的输出节点为 3
fc = tf.keras.layers.Dense(3) 
# 定义全连接层的输入节点为 4
fc.build(input_shape=(2,4)) 
# 查看权值矩阵 W
fc.kernel 

<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.68623924, -0.3229205 , -0.8148483 ],
       [-0.5391494 ,  0.9252815 , -0.91155016],
       [ 0.71436787, -0.21712309,  0.642977  ],
       [ 0.52107406,  0.8063965 , -0.4416557 ]], dtype=float32)>

### 三维张量

In [50]:
# 自动加载 IMDB 电影评价数据集
(x_train,y_train),(x_test,y_test)=keras.datasets.imdb.load_data(num_words=10000)
# 将句子填充、截断为等长 80 个单词的句子
x_train = keras.preprocessing.sequence.pad_sequences(x_train,maxlen=80)
x_train.shape

(25000, 80)

可以看到 x_train 张量的 shape 为[25000,80]，其中 25000 表示句子个数， 80 表示每个句子共 80 个单词，每个单词使用数字编码方式表示。

我们通过 layers.Embedding 层将数字编码的单词转换为长度为 100 个词向量：

In [51]:
# 创建词向量 Embedding 层类
embedding = tf.keras.layers.Embedding(10000, 100)
# 将数字编码的单词转换为词向量
out = embedding(x_train)
out.shape

TensorShape([25000, 80, 100])

可以看到，经过 Embedding 层编码后，句子张量的 shape 变为[25000,80,100]，其中 100 表示每个单词编码为长度是 100 的向量。

### 四维张量

In [52]:
# 创建 32x32 的彩色图片输入，个数为 4
x = tf.random.normal([4,32,32,3])
# 创建卷积神经网络
layer = layers.Conv2D(16, kernel_size=3)
# 前向计算
out = layer(x) 
# 输出大小
out.shape 

TensorShape([4, 30, 30, 16])

In [53]:
# 访问卷积核张量
layer.kernel.shape 

TensorShape([3, 3, 3, 16])

## 索引与切片
### 索引

In [54]:
# 创建4维张量
x = tf.random.normal([4,32,32,3]) 

In [55]:
# 取第 1 张图片的数据
x[0]

<tf.Tensor: id=267, shape=(32, 32, 3), dtype=float32, numpy=
array([[[ 2.99530417e-01,  4.98727709e-01,  4.62626219e-02],
        [-3.96997780e-01, -6.82494998e-01,  8.39108825e-01],
        [-7.75049552e-02,  4.21769395e-02, -2.66631067e-01],
        ...,
        [ 9.24115896e-01,  1.11348259e+00, -1.98075920e-03],
        [ 9.75685492e-02,  3.15199792e-01,  1.45533215e-03],
        [-9.43217650e-02, -3.38576585e-01, -9.09859657e-01]],

       [[ 8.26262116e-01, -4.33892906e-01,  1.25799692e+00],
        [ 2.21274532e-02,  3.34542483e-01,  1.09432912e+00],
        [-1.14753687e+00, -7.91423619e-02,  1.20629835e+00],
        ...,
        [ 7.84798443e-01,  1.27108026e+00,  4.95129377e-01],
        [ 1.85994245e-02, -1.77249837e+00, -2.46315432e+00],
        [-6.89060912e-02,  1.20367475e-01,  1.67715049e+00]],

       [[ 1.56032932e+00,  1.92112529e+00, -2.72057831e-01],
        [ 5.39079487e-01, -1.07490349e+00,  8.35203767e-01],
        [-1.58621490e+00, -1.28948975e+00, -1.09115577e

In [56]:
# 取第 1 张图片的第 2 行
x[0][1]

<tf.Tensor: id=275, shape=(32, 3), dtype=float32, numpy=
array([[ 0.8262621 , -0.4338929 ,  1.2579969 ],
       [ 0.02212745,  0.33454248,  1.0943291 ],
       [-1.1475369 , -0.07914236,  1.2062984 ],
       [-1.686936  ,  0.68173933,  0.3722031 ],
       [-0.15089631, -0.24881049, -0.33793926],
       [-0.6563053 ,  0.31180674, -0.4290292 ],
       [-1.052107  ,  0.5420052 ,  1.5521606 ],
       [-0.70863354,  0.77011514, -1.0246024 ],
       [ 1.009102  ,  0.63487196,  2.4887757 ],
       [ 0.30981743, -2.2108316 ,  0.22299956],
       [ 0.46953636, -1.4177477 , -1.3258795 ],
       [ 0.70513606, -0.03387154, -1.9069157 ],
       [ 0.29166472,  0.49272627,  0.48349282],
       [-1.2451935 , -0.40504304,  0.7758409 ],
       [ 0.512887  , -1.5394231 , -1.1045772 ],
       [-1.8578997 , -0.19047123, -1.0916772 ],
       [-1.168929  ,  0.68927103,  1.4155049 ],
       [-0.3986797 , -0.3218197 ,  0.220516  ],
       [-1.4762087 , -1.0211982 , -0.03255003],
       [ 0.52727026,  1.81834  

In [57]:
# 取第 1 张图片，第 2 行，第 3 列的数据
x[0][1][2]

<tf.Tensor: id=287, shape=(3,), dtype=float32, numpy=array([-1.1475369 , -0.07914236,  1.2062984 ], dtype=float32)>

In [58]:
# 取第 3 张图片，第 2 行，第 1 列的像素， B 通道(第 2 个通道)颜色强度值
x[2][1][0][1]

<tf.Tensor: id=303, shape=(), dtype=float32, numpy=-2.9019375>

In [59]:
# 取第 2 张图片，第 10 行，第 3 列的数据
x[1,9,2]

<tf.Tensor: id=307, shape=(3,), dtype=float32, numpy=array([ 1.485031  , -1.2768915 , -0.00464185], dtype=float32)>

### 切片

In [60]:
# 读取第 2,3 张图片
x[1:3]

<tf.Tensor: id=311, shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 8.46740842e-01,  1.80739868e+00,  1.66958928e-01],
         [-2.60244519e-01,  5.12237549e-01,  1.11330593e+00],
         [ 6.59267247e-01,  2.35228110e-02, -1.97934294e+00],
         ...,
         [-1.64584064e+00, -1.13802111e+00, -8.40150043e-02],
         [ 2.06940722e+00,  7.20250368e-01,  2.33594012e+00],
         [ 1.62608635e+00, -4.61122364e-01, -1.54706681e+00]],

        [[ 1.96481615e-01,  3.87161821e-02,  6.49615705e-01],
         [-2.20786884e-01, -5.71757376e-01,  8.32434595e-01],
         [ 8.93542469e-01,  1.61621594e+00, -1.13300335e+00],
         ...,
         [-6.02387249e-01,  5.74446261e-01, -8.82000476e-02],
         [ 7.14025319e-01,  5.32498479e-01, -1.09378779e+00],
         [-5.84288388e-02,  3.41455847e-01,  7.71340623e-04]],

        [[ 1.27693522e+00, -5.58431864e-01,  2.36351594e-01],
         [ 1.65726399e+00,  9.85945985e-02,  1.76614061e-01],
         [ 4.03812349e-01, -1.626421

In [61]:
# 读取第一张图片
x[0,::] 

<tf.Tensor: id=315, shape=(32, 32, 3), dtype=float32, numpy=
array([[[ 2.99530417e-01,  4.98727709e-01,  4.62626219e-02],
        [-3.96997780e-01, -6.82494998e-01,  8.39108825e-01],
        [-7.75049552e-02,  4.21769395e-02, -2.66631067e-01],
        ...,
        [ 9.24115896e-01,  1.11348259e+00, -1.98075920e-03],
        [ 9.75685492e-02,  3.15199792e-01,  1.45533215e-03],
        [-9.43217650e-02, -3.38576585e-01, -9.09859657e-01]],

       [[ 8.26262116e-01, -4.33892906e-01,  1.25799692e+00],
        [ 2.21274532e-02,  3.34542483e-01,  1.09432912e+00],
        [-1.14753687e+00, -7.91423619e-02,  1.20629835e+00],
        ...,
        [ 7.84798443e-01,  1.27108026e+00,  4.95129377e-01],
        [ 1.85994245e-02, -1.77249837e+00, -2.46315432e+00],
        [-6.89060912e-02,  1.20367475e-01,  1.67715049e+00]],

       [[ 1.56032932e+00,  1.92112529e+00, -2.72057831e-01],
        [ 5.39079487e-01, -1.07490349e+00,  8.35203767e-01],
        [-1.58621490e+00, -1.28948975e+00, -1.09115577e

In [62]:
x[:,0:28:2,0:28:2,:]

<tf.Tensor: id=319, shape=(4, 14, 14, 3), dtype=float32, numpy=
array([[[[ 0.29953042,  0.4987277 ,  0.04626262],
         [-0.07750496,  0.04217694, -0.26663107],
         [ 0.24735   ,  1.6950517 ,  0.02992302],
         ...,
         [ 2.0477266 , -2.0233023 ,  1.0728284 ],
         [-0.17582789,  0.0784962 , -0.9059661 ],
         [ 0.31916165,  0.82557184,  0.85820985]],

        [[ 1.5603293 ,  1.9211253 , -0.27205783],
         [-1.5862149 , -1.2894897 , -1.0911558 ],
         [-0.07426735,  0.32746324,  0.813031  ],
         ...,
         [ 0.6618759 , -0.19002001, -1.1807245 ],
         [-0.41493273, -1.7765453 ,  0.05143803],
         [ 1.0719932 , -0.16450751, -0.15150851]],

        [[-0.5754298 , -0.0058106 ,  0.22331402],
         [-0.5108397 ,  0.67866975,  0.06346172],
         [ 1.0004263 , -0.1551236 ,  1.3412995 ],
         ...,
         [ 1.3273468 , -0.3039278 , -1.2280399 ],
         [ 0.9735842 ,  0.27331632, -2.1884685 ],
         [-0.47231004, -1.2463309 , -1.3

In [63]:
# 考虑一个 0~9 的简单序列向量， 逆序取到第 1 号元素，不包含第 1 号
# 创建 0~9 向量
x = tf.range(9) 
# 从 8 取到 0，逆序，不包含 0
x[8:0:-1] 

<tf.Tensor: id=327, shape=(8,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1])>

In [64]:
# 逆序全部元素
x[::-1] 

<tf.Tensor: id=331, shape=(9,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1, 0])>

In [65]:
# 逆序间隔采样
x[::-2] 

<tf.Tensor: id=335, shape=(5,), dtype=int32, numpy=array([8, 6, 4, 2, 0])>

读取每张图片的所有通道，其中行按着逆序隔行采样，列按着逆序隔行采样

In [66]:
x = tf.random.normal([4,32,32,3])
# 行、列逆序间隔采样
x[0,::-2,::-2] 

<tf.Tensor: id=345, shape=(16, 16, 3), dtype=float32, numpy=
array([[[-1.30231440e+00, -2.75677502e-01, -9.97396588e-01],
        [-1.63859499e+00, -1.82385838e+00, -1.23019147e+00],
        [-2.82821298e-01, -1.23738873e+00, -5.99224985e-01],
        [ 6.61249161e-01, -1.62893391e+00, -7.22544193e-01],
        [ 1.78936660e+00,  1.33216929e+00, -6.87687278e-01],
        [ 1.60941228e-01,  6.05650902e-01, -1.20217228e+00],
        [-7.69305527e-01,  5.85967124e-01,  1.46998489e+00],
        [ 1.18222041e-02,  3.29580367e-01,  5.46027541e-01],
        [-7.05268025e-01,  1.56249356e+00,  1.55947298e-01],
        [ 6.88953102e-01, -8.85246158e-01, -2.32767284e-01],
        [-2.33633304e+00, -8.38297725e-01, -6.72355950e-01],
        [ 4.87224847e-01,  6.14003956e-01,  3.77696306e-01],
        [ 6.13961406e-02, -2.47145987e+00,  9.32613492e-01],
        [ 1.30616307e-01, -8.11282635e-01, -1.05657315e+00],
        [ 8.58024836e-01, -2.08463162e-01,  1.58311427e-01],
        [-1.97587907e+00

In [67]:
# 取 G 通道数据
x[:,:,:,1] 

<tf.Tensor: id=349, shape=(4, 32, 32), dtype=float32, numpy=
array([[[ 1.4163171 , -0.99100363,  0.9727313 , ..., -0.14283776,
          0.7318449 , -0.05178464],
        [ 0.06339532, -0.45184296,  0.25942248, ..., -0.06245631,
          0.93556476, -0.03587704],
        [ 0.50663936,  0.54724914,  1.3512745 , ..., -0.44103754,
         -0.51950544,  0.17756358],
        ...,
        [ 0.8763012 ,  0.34712338,  0.08650679, ...,  0.29039204,
          1.0828719 ,  0.21577203],
        [ 0.01343326,  0.9105041 ,  0.0269085 , ...,  0.39361376,
          1.3617097 ,  0.9417917 ],
        [ 1.600958  , -2.006091  ,  0.61326146, ..., -1.8238584 ,
          2.117606  , -0.2756775 ]],

       [[ 1.0703735 ,  1.4782596 ,  0.12009769, ...,  0.38401797,
          0.04191272,  0.52485675],
        [-0.41840804,  1.4454169 , -0.10964448, ...,  1.0799342 ,
          0.5817725 ,  0.07210258],
        [ 0.74234515, -0.24507006, -1.4578117 , ...,  0.78528863,
          0.38497218, -0.26053986],
      

In [68]:
# 读取第 1~2 张图片的 G/B 通道数据
# 高宽维度全部采集
x[0:2,...,1:] 

<tf.Tensor: id=353, shape=(2, 32, 32, 2), dtype=float32, numpy=
array([[[[ 1.4163171 , -0.7690393 ],
         [-0.99100363,  0.58865726],
         [ 0.9727313 , -1.3791904 ],
         ...,
         [-0.14283776,  0.22880542],
         [ 0.7318449 , -1.574153  ],
         [-0.05178464,  2.4106843 ]],

        [[ 0.06339532,  0.65484357],
         [-0.45184296,  0.4325734 ],
         [ 0.25942248,  1.9919096 ],
         ...,
         [-0.06245631,  0.306167  ],
         [ 0.93556476,  0.8361039 ],
         [-0.03587704, -0.37716332]],

        [[ 0.50663936,  1.9259235 ],
         [ 0.54724914, -1.0042543 ],
         [ 1.3512745 ,  0.4089729 ],
         ...,
         [-0.44103754, -0.64622813],
         [-0.51950544,  1.4431831 ],
         [ 0.17756358,  0.10349176]],

        ...,

        [[ 0.8763012 ,  0.22065912],
         [ 0.34712338,  1.073838  ],
         [ 0.08650679, -1.6869181 ],
         ...,
         [ 0.29039204,  0.64912045],
         [ 1.0828719 , -0.12624674],
         

In [69]:
# 读取最后 2 张图片
# 高、宽、通道维度全部采集，等价于 x[2:]
x[2:,...] 

<tf.Tensor: id=357, shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 0.10016768,  0.02867392,  0.02509212],
         [-1.37642   ,  0.2764482 ,  1.4171727 ],
         [-0.24855998,  0.28951004, -0.7084009 ],
         ...,
         [-0.80414665, -2.2164378 ,  0.57747734],
         [ 0.94737893, -0.37068766,  0.34749508],
         [ 2.0098033 ,  0.5199307 ,  0.39188537]],

        [[-0.813648  , -0.48181632, -0.0441347 ],
         [-1.4751934 ,  0.32555372, -0.07609986],
         [ 1.2997733 ,  1.7738433 ,  0.39246076],
         ...,
         [-1.2471989 ,  1.8274868 ,  0.26184738],
         [ 1.8727727 ,  1.9262378 ,  0.2938723 ],
         [ 1.2489593 ,  1.4781617 ,  1.1826677 ]],

        [[ 0.5581632 , -0.61703444,  0.85014933],
         [ 0.8112494 , -0.9920038 , -0.18897657],
         [ 2.3027737 ,  0.16347714, -2.1211443 ],
         ...,
         [ 0.05707187, -1.5277367 , -0.6178113 ],
         [ 0.17470706, -0.26580867, -1.0753275 ],
         [-0.70576775, -0.93169016,  1.2

In [70]:
# 读取 R/G 通道数据
# 所有样本，所有高、宽的前 2 个通道
x[...,:2] 

<tf.Tensor: id=361, shape=(4, 32, 32, 2), dtype=float32, numpy=
array([[[[-0.15501821,  1.4163171 ],
         [ 0.13188218, -0.99100363],
         [ 0.13047694,  0.9727313 ],
         ...,
         [ 0.33833382, -0.14283776],
         [ 1.0042797 ,  0.7318449 ],
         [ 0.20474268, -0.05178464]],

        [[-0.15079647,  0.06339532],
         [ 1.0642016 , -0.45184296],
         [-1.8020998 ,  0.25942248],
         ...,
         [ 0.7711484 , -0.06245631],
         [-1.3013368 ,  0.93556476],
         [-2.0110266 , -0.03587704]],

        [[ 1.5875183 ,  0.50663936],
         [ 1.2086841 ,  0.54724914],
         [-0.11268201,  1.3512745 ],
         ...,
         [ 0.5017021 , -0.44103754],
         [-0.68322235, -0.51950544],
         [ 0.31125382,  0.17756358]],

        ...,

        [[-1.7715315 ,  0.8763012 ],
         [ 0.8799027 ,  0.34712338],
         [ 0.57395184,  0.08650679],
         ...,
         [-0.07819584,  0.29039204],
         [ 0.6956597 ,  1.0828719 ],
         

## 维度变换

### 改变视图

In [71]:
# 生成向量
x=tf.range(96)
# 改变 x 的视图，获得 4D 张量，存储并未改变
x=tf.reshape(x,[2,4,4,3]) 
x

<tf.Tensor: id=367, shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]])>

### 改变视图

我们通过 tf.range()模拟生成一个向量数据，并通过 tf.reshape 视图改变函数产生不同的视图

In [72]:
# 生成向量
x = tf.range(96) 
# 改变 x 的视图，获得 4D 张量，存储并未改变
x = tf.reshape(x,[2,4,4,3]) 
x

<tf.Tensor: id=373, shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]])>

In [73]:
# 获取张量的维度数和形状列表
x.ndim,x.shape 

(4, TensorShape([2, 4, 4, 3]))

通过 tf.reshape(x, new_shape)，可以将张量的视图任意地合法改变

In [74]:
tf.reshape(x,[2,-1])

<tf.Tensor: id=375, shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]])>

In [75]:
 tf.reshape(x,[2,4,12])

<tf.Tensor: id=377, shape=(2, 4, 12), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]]])>

In [76]:
tf.reshape(x,[2,-1,3])

<tf.Tensor: id=379, shape=(2, 16, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59],
        [60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71],
        [72, 73, 74],
        [75, 76, 77],
        [78, 79, 80],
        [81, 82, 83],
        [84, 85, 86],
        [87, 88, 89],
        [90, 91, 92],
        [93, 94, 95]]])>

### 增、 删维度

In [77]:
# 产生矩阵
x = tf.random.uniform([28,28],maxval=10,dtype=tf.int32)
x

<tf.Tensor: id=383, shape=(28, 28), dtype=int32, numpy=
array([[3, 1, 4, 5, 1, 1, 2, 7, 3, 2, 0, 4, 8, 6, 1, 1, 9, 2, 7, 8, 8, 5,
        3, 1, 6, 3, 3, 7],
       [9, 2, 9, 3, 4, 8, 2, 9, 9, 3, 6, 4, 5, 6, 6, 5, 5, 0, 7, 0, 1, 5,
        4, 4, 6, 7, 4, 8],
       [1, 7, 1, 1, 8, 4, 1, 7, 1, 2, 1, 5, 9, 7, 3, 1, 5, 4, 7, 6, 0, 1,
        6, 6, 7, 4, 1, 2],
       [3, 4, 5, 8, 8, 6, 9, 6, 3, 6, 9, 2, 8, 0, 7, 4, 4, 9, 9, 2, 9, 9,
        3, 1, 9, 8, 9, 3],
       [9, 9, 7, 3, 5, 4, 4, 6, 7, 3, 8, 0, 3, 3, 8, 3, 2, 2, 5, 2, 3, 8,
        7, 7, 7, 3, 0, 4],
       [8, 5, 5, 2, 4, 4, 3, 6, 3, 1, 0, 7, 4, 9, 2, 8, 6, 3, 2, 6, 4, 5,
        3, 9, 6, 8, 0, 7],
       [2, 4, 4, 9, 2, 4, 2, 3, 0, 3, 7, 5, 5, 9, 6, 1, 8, 4, 7, 8, 5, 7,
        1, 1, 4, 8, 1, 8],
       [5, 0, 9, 5, 9, 0, 2, 8, 9, 8, 1, 4, 1, 4, 5, 9, 3, 5, 6, 5, 7, 5,
        0, 2, 9, 1, 1, 8],
       [3, 0, 2, 7, 8, 5, 3, 1, 9, 1, 5, 1, 7, 8, 6, 6, 1, 9, 2, 6, 7, 1,
        7, 6, 2, 6, 0, 9],
       [7, 3, 8, 8, 9, 6, 2, 4, 8, 

通过 tf.expand_dims(x, axis)可在指定的 axis 轴前可以插入一个新的维度

In [78]:
# axis=2 表示宽维度后面的一个维度
x = tf.expand_dims(x,axis=2) 
x

<tf.Tensor: id=385, shape=(28, 28, 1), dtype=int32, numpy=
array([[[3],
        [1],
        [4],
        [5],
        [1],
        [1],
        [2],
        [7],
        [3],
        [2],
        [0],
        [4],
        [8],
        [6],
        [1],
        [1],
        [9],
        [2],
        [7],
        [8],
        [8],
        [5],
        [3],
        [1],
        [6],
        [3],
        [3],
        [7]],

       [[9],
        [2],
        [9],
        [3],
        [4],
        [8],
        [2],
        [9],
        [9],
        [3],
        [6],
        [4],
        [5],
        [6],
        [6],
        [5],
        [5],
        [0],
        [7],
        [0],
        [1],
        [5],
        [4],
        [4],
        [6],
        [7],
        [4],
        [8]],

       [[1],
        [7],
        [1],
        [1],
        [8],
        [4],
        [1],
        [7],
        [1],
        [2],
        [1],
        [5],
        [9],
        [7],
        [3],
        [1],
 

In [79]:
x = tf.expand_dims(x,axis=0) # 高维度之前插入新维度
x

<tf.Tensor: id=387, shape=(1, 28, 28, 1), dtype=int32, numpy=
array([[[[3],
         [1],
         [4],
         [5],
         [1],
         [1],
         [2],
         [7],
         [3],
         [2],
         [0],
         [4],
         [8],
         [6],
         [1],
         [1],
         [9],
         [2],
         [7],
         [8],
         [8],
         [5],
         [3],
         [1],
         [6],
         [3],
         [3],
         [7]],

        [[9],
         [2],
         [9],
         [3],
         [4],
         [8],
         [2],
         [9],
         [9],
         [3],
         [6],
         [4],
         [5],
         [6],
         [6],
         [5],
         [5],
         [0],
         [7],
         [0],
         [1],
         [5],
         [4],
         [4],
         [6],
         [7],
         [4],
         [8]],

        [[1],
         [7],
         [1],
         [1],
         [8],
         [4],
         [1],
         [7],
         [1],
         [2],
         [

In [80]:
x = tf.squeeze(x, axis=0) # 删除图片数量维度
x

<tf.Tensor: id=388, shape=(28, 28, 1), dtype=int32, numpy=
array([[[3],
        [1],
        [4],
        [5],
        [1],
        [1],
        [2],
        [7],
        [3],
        [2],
        [0],
        [4],
        [8],
        [6],
        [1],
        [1],
        [9],
        [2],
        [7],
        [8],
        [8],
        [5],
        [3],
        [1],
        [6],
        [3],
        [3],
        [7]],

       [[9],
        [2],
        [9],
        [3],
        [4],
        [8],
        [2],
        [9],
        [9],
        [3],
        [6],
        [4],
        [5],
        [6],
        [6],
        [5],
        [5],
        [0],
        [7],
        [0],
        [1],
        [5],
        [4],
        [4],
        [6],
        [7],
        [4],
        [8]],

       [[1],
        [7],
        [1],
        [1],
        [8],
        [4],
        [1],
        [7],
        [1],
        [2],
        [1],
        [5],
        [9],
        [7],
        [3],
        [1],
 

In [81]:
x = tf.random.uniform([1,28,28,1],maxval=10,dtype=tf.int32)
tf.squeeze(x) # 删除所有长度为 1 的维度

<tf.Tensor: id=393, shape=(28, 28), dtype=int32, numpy=
array([[1, 2, 2, 6, 9, 9, 5, 4, 6, 6, 3, 2, 3, 8, 8, 0, 3, 2, 2, 1, 7, 4,
        1, 0, 1, 7, 0, 9],
       [1, 3, 5, 3, 5, 8, 1, 5, 7, 7, 2, 8, 4, 8, 3, 4, 4, 5, 6, 5, 9, 9,
        6, 0, 1, 1, 0, 6],
       [9, 0, 9, 0, 3, 6, 1, 3, 3, 8, 2, 9, 5, 9, 2, 7, 8, 6, 3, 6, 8, 6,
        0, 7, 7, 2, 0, 8],
       [4, 1, 7, 5, 9, 7, 4, 4, 2, 9, 2, 1, 8, 8, 0, 6, 5, 1, 5, 8, 0, 1,
        4, 1, 4, 0, 3, 9],
       [1, 6, 9, 3, 8, 3, 5, 2, 6, 8, 3, 3, 6, 0, 4, 4, 8, 8, 8, 7, 0, 5,
        0, 7, 9, 4, 9, 3],
       [1, 8, 2, 3, 6, 6, 8, 3, 1, 5, 9, 2, 6, 6, 8, 8, 6, 3, 0, 4, 8, 5,
        4, 6, 7, 0, 6, 3],
       [1, 0, 1, 2, 6, 4, 7, 3, 9, 3, 7, 4, 8, 8, 0, 6, 5, 2, 8, 3, 9, 8,
        3, 9, 4, 9, 1, 1],
       [0, 7, 0, 7, 4, 1, 3, 3, 5, 6, 9, 3, 8, 9, 2, 1, 4, 1, 1, 6, 6, 1,
        8, 8, 1, 6, 1, 9],
       [6, 8, 4, 4, 4, 5, 7, 7, 9, 7, 1, 5, 1, 6, 3, 2, 2, 3, 2, 0, 5, 6,
        1, 1, 0, 4, 5, 8],
       [3, 8, 4, 4, 7, 0, 1, 1, 0, 

### 交换维度

In [82]:
x = tf.random.normal([2,32,32,3])
# 交换维度
tf.transpose(x,perm=[0,3,1,2]) 

<tf.Tensor: id=401, shape=(2, 3, 32, 32), dtype=float32, numpy=
array([[[[-0.39043707, -0.30230662, -1.9867934 , ..., -0.29216716,
          -0.64319944,  1.5930222 ],
         [-0.6313358 ,  1.6687986 ,  0.7610653 , ...,  0.5870873 ,
           0.73140526,  1.2941878 ],
         [ 1.0156972 , -0.29763278, -1.0652418 , ..., -0.48389727,
          -1.4059663 ,  0.41628385],
         ...,
         [-1.7150276 ,  0.19418778, -0.66255295, ..., -0.62195665,
          -0.73488826, -0.4232543 ],
         [-0.73697793,  1.012251  ,  0.15486401, ...,  0.860078  ,
           0.8544123 ,  0.5678252 ],
         [-1.8589381 , -1.3342535 ,  0.9935424 , ...,  0.25716868,
          -2.015309  , -0.85078555]],

        [[-0.17664903,  0.8847422 , -0.46457696, ...,  0.92455554,
          -0.60910517, -0.18064296],
         [ 0.75812924,  0.0237945 , -1.9612142 , ..., -0.45630676,
          -0.28309876, -1.2331525 ],
         [-0.01368176, -0.5026539 ,  1.2290294 , ..., -1.1423604 ,
          -0.3260375 

In [83]:
x = tf.random.normal([2,32,32,3])
# 交换维度
tf.transpose(x,perm=[0,2,1,3]) 

<tf.Tensor: id=409, shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[-7.05858529e-01,  5.79857349e-01,  5.17978489e-01],
         [ 1.97535038e-01,  2.41262150e+00, -8.08618605e-01],
         [-1.33387029e+00,  8.35422397e-01,  4.68417741e-02],
         ...,
         [-1.85486555e+00, -1.79760963e-01, -1.30834386e-01],
         [ 1.74203920e+00,  8.04924190e-01,  5.22668839e-01],
         [ 1.16469514e+00, -9.97500345e-02, -3.65659148e-01]],

        [[-4.97209340e-01,  3.06787133e-01, -3.69988382e-01],
         [-2.90299535e-01, -5.25915980e-01,  1.27274334e+00],
         [ 1.84384391e-01, -3.07884425e-01, -1.85154855e+00],
         ...,
         [-3.15949917e-01,  3.61859918e-01,  1.17602742e+00],
         [ 6.25441253e-01, -5.67000389e-01,  8.02632213e-01],
         [ 6.11567736e-01,  1.57166350e+00,  4.98567879e-01]],

        [[-9.19834495e-01, -4.40173537e-01, -2.29611695e-01],
         [ 9.47837830e-01, -5.55911660e-01,  4.74197090e-01],
         [-1.72871817e-02,  2.211458

### 复制数据

In [84]:
# 创建向量 b
b = tf.constant([1,2]) 
# 插入新维度，变成矩阵
b = tf.expand_dims(b, axis=0) 
b

<tf.Tensor: id=412, shape=(1, 2), dtype=int32, numpy=array([[1, 2]])>

In [85]:
# 样本维度上复制一份
b = tf.tile(b, multiples=[2,1]) 
b

<tf.Tensor: id=414, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2]])>

In [86]:
x = tf.range(4)
# 创建 2 行 2 列矩阵
x=tf.reshape(x,[2,2]) 
x

<tf.Tensor: id=420, shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]])>

In [87]:
# 列维度复制一份
x = tf.tile(x,multiples=[1,2]) 
x

<tf.Tensor: id=422, shape=(2, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3]])>

In [88]:
# 行维度复制一份
x = tf.tile(x,multiples=[2,1]) 
x

<tf.Tensor: id=424, shape=(4, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]])>

## Broadcasting

In [89]:
# 创建矩阵
A = tf.random.normal([32,1]) 
# 扩展为 4D 张量
tf.broadcast_to(A, [2,32,32,3]) 

<tf.Tensor: id=432, shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[-0.17697057, -0.17697057, -0.17697057],
         [-1.3640729 , -1.3640729 , -1.3640729 ],
         [ 0.49448076,  0.49448076,  0.49448076],
         ...,
         [ 0.42191896,  0.42191896,  0.42191896],
         [-0.95125973, -0.95125973, -0.95125973],
         [-1.2678576 , -1.2678576 , -1.2678576 ]],

        [[-0.17697057, -0.17697057, -0.17697057],
         [-1.3640729 , -1.3640729 , -1.3640729 ],
         [ 0.49448076,  0.49448076,  0.49448076],
         ...,
         [ 0.42191896,  0.42191896,  0.42191896],
         [-0.95125973, -0.95125973, -0.95125973],
         [-1.2678576 , -1.2678576 , -1.2678576 ]],

        [[-0.17697057, -0.17697057, -0.17697057],
         [-1.3640729 , -1.3640729 , -1.3640729 ],
         [ 0.49448076,  0.49448076,  0.49448076],
         ...,
         [ 0.42191896,  0.42191896,  0.42191896],
         [-0.95125973, -0.95125973, -0.95125973],
         [-1.2678576 , -1.2678576 , -1.2

In [90]:
A = tf.random.normal([32,2])
# 不符合 Broadcasting 条件
try: 
    tf.broadcast_to(A, [2,32,32,4])
except Exception as e:
    print(e)

Incompatible shapes: [32,2] vs. [2,32,32,4] [Op:BroadcastTo]


## 数学运算

### 加、 减、 乘、 除运算

In [91]:
a = tf.range(5)
b = tf.constant(2)
# 整除运算
a//b 

<tf.Tensor: id=445, shape=(5,), dtype=int32, numpy=array([0, 0, 1, 1, 2])>

In [92]:
# 余除运算
a%b 

<tf.Tensor: id=446, shape=(5,), dtype=int32, numpy=array([0, 1, 0, 1, 0])>

### 乘方运算

In [93]:
x = tf.range(4)
# 乘方运算
tf.pow(x,3) 

<tf.Tensor: id=452, shape=(4,), dtype=int32, numpy=array([ 0,  1,  8, 27])>

In [94]:
# 乘方运算符
x**2 

<tf.Tensor: id=454, shape=(4,), dtype=int32, numpy=array([0, 1, 4, 9])>

In [95]:
x=tf.constant([1.,4.,9.])
# 平方根
x**(0.5) 

<tf.Tensor: id=457, shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [96]:
x = tf.range(5)
# 转换为浮点数
x = tf.cast(x, dtype=tf.float32) 
# 平方
x = tf.square(x) 

In [97]:
# 平方根
tf.sqrt(x) 

<tf.Tensor: id=464, shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

### 指数和对数运算

In [98]:
x = tf.constant([1.,2.,3.])
# 指数运算
2**x 

<tf.Tensor: id=467, shape=(3,), dtype=float32, numpy=array([2., 4., 8.], dtype=float32)>

In [99]:
# 自然指数运算
tf.exp(1.)

<tf.Tensor: id=469, shape=(), dtype=float32, numpy=2.7182817>

In [100]:
x = tf.exp(3.)
# 对数运算
tf.math.log(x) 

<tf.Tensor: id=472, shape=(), dtype=float32, numpy=3.0>

In [101]:
x = tf.constant([1.,2.])
x = 10**x
# 换底公式
tf.math.log(x)/tf.math.log(10.) 

<tf.Tensor: id=479, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

### 矩阵相乘运算

In [102]:
a = tf.random.normal([4,3,28,32])
b = tf.random.normal([4,3,32,2])
# 批量形式的矩阵相乘
a@b

<tf.Tensor: id=492, shape=(4, 3, 28, 2), dtype=float32, numpy=
array([[[[ 5.94066811e+00,  3.84594083e+00],
         [ 3.57476473e+00,  7.56964827e+00],
         [ 2.49250174e+00,  1.75833244e+01],
         [-7.17508793e+00,  1.18989730e+00],
         [-4.78235865e+00, -5.54538298e+00],
         [ 6.75838518e+00, -5.58561420e+00],
         [-6.56471252e+00, -3.39151645e+00],
         [-9.42782402e+00, -1.00086164e+00],
         [ 2.36318350e+00,  2.80893636e+00],
         [-2.47026467e+00, -4.17602777e+00],
         [-1.23877680e+00, -4.58212948e+00],
         [-1.00558939e+01, -8.20680714e+00],
         [ 6.02279329e+00,  1.01278186e-01],
         [-7.33531809e+00, -2.63454843e+00],
         [ 2.67623734e+00, -1.01776285e+01],
         [ 3.92479748e-01, -1.58483016e+00],
         [ 2.57540178e+00, -3.39094019e+00],
         [ 5.56058550e+00, -9.60079575e+00],
         [-4.30204344e+00, -2.94906044e+00],
         [ 9.48721790e+00,  7.12444448e+00],
         [ 2.47954512e+00,  1.0553787

In [103]:
a = tf.random.normal([4,28,32])
b = tf.random.normal([32,16])
# 先自动扩展，再矩阵相乘
tf.matmul(a,b)

<tf.Tensor: id=505, shape=(4, 28, 16), dtype=float32, numpy=
array([[[-2.84560680e+00,  7.30936241e+00, -1.03762007e+00, ...,
          1.82498300e+00, -8.35795021e+00,  1.42563486e+00],
        [-7.58373737e+00, -1.02390079e+01, -1.14226131e+01, ...,
         -1.22444427e+00,  1.84023166e+00,  1.21027775e+01],
        [ 6.34778833e+00,  7.68865585e-01,  6.99941516e-01, ...,
         -2.39015055e+00,  1.90107465e+00,  7.44709671e-01],
        ...,
        [ 5.44278765e+00,  1.07757645e+01, -5.84262323e+00, ...,
          3.85940599e+00, -1.17176085e+01, -1.01847738e-01],
        [-1.73742599e+01, -1.70520759e+00,  2.86395526e+00, ...,
          1.16156511e+01,  8.45351982e+00, -1.32909698e+01],
        [ 3.52394772e+00,  5.09220362e-01, -4.44947624e+00, ...,
          5.67079830e+00,  1.08710563e+00,  1.13338366e+01]],

       [[ 1.06613169e+01, -9.25686836e+00,  4.69081926e+00, ...,
          4.33271646e+00,  1.38469667e+01, -7.73081005e-01],
        [ 3.11241174e+00,  8.71088505e+00,

## 前向传播实战

In [104]:
import tensorflow.keras.datasets as datasets
# 加载 MNIST 数据集
(x, y), (x_val, y_val) = datasets.mnist.load_data()

In [105]:
# 每层的张量都需要被优化，故使用 Variable 类型，并使用截断的正太分布初始化权值张量
# 偏置向量初始化为 0 即可
# 第一层的参数
w1 = tf.Variable(tf.random.truncated_normal([784, 256], stddev=0.1))
b1 = tf.Variable(tf.zeros([256]))
# 第二层的参数
w2 = tf.Variable(tf.random.truncated_normal([256, 128], stddev=0.1))
b2 = tf.Variable(tf.zeros([128]))
# 第三层的参数
w3 = tf.Variable(tf.random.truncated_normal([128, 10], stddev=0.1))
b3 = tf.Variable(tf.zeros([10]))

In [106]:
# 改变视图， [b, 28, 28] => [b, 28*28]
x = tf.reshape(x, (-1, 28*28))
# 第一层计算， [b, 784]@[784, 256] + [256] => [b, 256] + [256] => [b,256] + [b, 256]
h1 = x@w1 + tf.broadcast_to(b1, (x.shape[0], 256))
h1 = tf.nn.relu(h1) # 通过激活函数

NotFoundError: Could not find valid device for node.
Node:{{node MatMul}}
All kernels registered for op MatMul :
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_HALF]
  device='CPU'; label='eigen'; T in [DT_FLOAT]
  device='CPU'; label='eigen'; T in [DT_DOUBLE]
  device='CPU'; label='eigen'; T in [DT_HALF]
  device='CPU'; label='eigen'; T in [DT_BFLOAT16]
  device='CPU'; label='eigen'; T in [DT_INT32]
  device='CPU'; label='eigen'; T in [DT_INT64]
  device='CPU'; label='eigen'; T in [DT_COMPLEX64]
  device='CPU'; label='eigen'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT64]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
  device='GPU'; label='cublas'; T in [DT_FLOAT]
  device='GPU'; label='cublas'; T in [DT_DOUBLE]
  device='GPU'; label='cublas'; T in [DT_COMPLEX64]
  device='GPU'; label='cublas'; T in [DT_COMPLEX128]
  device='GPU'; label='cublas'; T in [DT_HALF]
 [Op:MatMul] name: matmul/

In [ ]:
# 第二层计算， [b, 256] => [b, 128]
h2 = h1@w2 + b2
h2 = tf.nn.relu(h2)
# 输出层计算， [b, 128] => [b, 10]
out = h2@w3 + b3

In [ ]:
# 计算网络输出与标签之间的均方差， mse = mean(sum(y-out)^2)
# [b, 10]
loss = tf.square(y_onehot - out)
# 误差标量， mean: scalar
loss = tf.reduce_mean(loss)

In [ ]:
# 自动梯度，需要求梯度的张量有[w1, b1, w2, b2, w3, b3]
grads = tape.gradient(loss, [w1, b1, w2, b2, w3, b3])

In [ ]:
# 梯度更新， assign_sub 将当前值减去参数值，原地更新
w1.assign_sub(lr * grads[0])
b1.assign_sub(lr * grads[1])
w2.assign_sub(lr * grads[2])
b2.assign_sub(lr * grads[3])
w3.assign_sub(lr * grads[4])
b3.assign_sub(lr * grads[5])